ROOT_DIR := $(CUR_DIR)../..

BUILD_DIR := $(ROOT_DIR)/build
OBJECT_DIR := $(BUILD_DIR)/object/$(BUILD_POSTFIX)
OUT_DIR := $(BUILD_DIR)/out/$(BUILD_POSTFIX)

SOURCE_DIR := $(CUR_DIR)source
INCLUDE_DIR := $(CUR_DIR)/include

AUTOGENERATED_DIRECTORIES := $(OBJECT_DIR) $(OUT_DIR)
TARGETS := $(addprefix $(OUT_DIR)/,$(TARGET_NAMES))
OBJECTS := $(addprefix $(OBJECT_DIR)/,$(addsuffix .o,$(SOURCES)))

.PHONY: all
all: $(TARGETS)

$(AUTOGENERATED_DIRECTORIES):
	@mkdir -p $@

CC = clang
CXX = clang++
AS = nasm
LD = ld.lld